# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team8-lsc-accounts-deployment
containerName: team8-lsc-accounts-container
serviceName: team8-lsc-accounts-service
appLabel: team8-lsc-accounts-app

replicaCount: 1

image:
  repository: group1-team3-lsc-accounts

service:
  nodePort: 30811


eazybankcommon:
  service:
    targetPort: 8080
  containerPort: 8080
  image:
    tag: v0.0.2