# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team8-cards
containerName: team8-cards
serviceName: team8-cards
appLabel: team8-cards

replicaCount: 1

image:
  repository: team8-cards

service:
  nodePort: 30812


eazybankcommon:
  service:
    targetPort: 8080
  containerPort: 8080
  image:
    tag: v0.0.1