# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team8-lsc-loans-deployment
containerName: team8-lsc-loans-container
serviceName: team8-lsc-loans-service
appLabel: team8-lsc-loans-app

replicaCount: 1

image:
  repository: group1-team8-lsc-loans


service:
  nodePort: 30813

eazybankcommon:
  service:
    targetPort: 8080
  containerPort: 8080
  image:
    tag: v0.0.1
